# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/spooled-cloud/spooled-sdk-go
  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
    # Exclude generated files
    - path: pb/
      linters:
        - all
    - path: types\.gen\.go
      linters:
        - all
    # Allow fmt.Print in examples
    - path: examples/
      linters:
        - forbidigo

