// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	AdminKeyAuthScopes = "AdminKeyAuth.Scopes"
	ApiKeyAuthScopes   = "ApiKeyAuth.Scopes"
	BearerAuthScopes   = "BearerAuth.Scopes"
)

// Defines values for AddDependenciesRequestDependencyMode.
const (
	AddDependenciesRequestDependencyModeAll AddDependenciesRequestDependencyMode = "all"
	AddDependenciesRequestDependencyModeAny AddDependenciesRequestDependencyMode = "any"
)

// Defines values for AdminCreateOrganizationRequestPlanTier.
const (
	AdminCreateOrganizationRequestPlanTierEnterprise AdminCreateOrganizationRequestPlanTier = "enterprise"
	AdminCreateOrganizationRequestPlanTierFree       AdminCreateOrganizationRequestPlanTier = "free"
	AdminCreateOrganizationRequestPlanTierPro        AdminCreateOrganizationRequestPlanTier = "pro"
	AdminCreateOrganizationRequestPlanTierStarter    AdminCreateOrganizationRequestPlanTier = "starter"
)

// Defines values for AdminUpdateOrganizationRequestPlanTier.
const (
	AdminUpdateOrganizationRequestPlanTierEnterprise AdminUpdateOrganizationRequestPlanTier = "enterprise"
	AdminUpdateOrganizationRequestPlanTierFree       AdminUpdateOrganizationRequestPlanTier = "free"
	AdminUpdateOrganizationRequestPlanTierPro        AdminUpdateOrganizationRequestPlanTier = "pro"
	AdminUpdateOrganizationRequestPlanTierStarter    AdminUpdateOrganizationRequestPlanTier = "starter"
)

// Defines values for AdminUpdateOrganizationRequestStripeSubscriptionStatus.
const (
	AdminUpdateOrganizationRequestStripeSubscriptionStatusActive     AdminUpdateOrganizationRequestStripeSubscriptionStatus = "active"
	AdminUpdateOrganizationRequestStripeSubscriptionStatusCanceled   AdminUpdateOrganizationRequestStripeSubscriptionStatus = "canceled"
	AdminUpdateOrganizationRequestStripeSubscriptionStatusIncomplete AdminUpdateOrganizationRequestStripeSubscriptionStatus = "incomplete"
	AdminUpdateOrganizationRequestStripeSubscriptionStatusPastDue    AdminUpdateOrganizationRequestStripeSubscriptionStatus = "past_due"
	AdminUpdateOrganizationRequestStripeSubscriptionStatusTrialing   AdminUpdateOrganizationRequestStripeSubscriptionStatus = "trialing"
	AdminUpdateOrganizationRequestStripeSubscriptionStatusUnpaid     AdminUpdateOrganizationRequestStripeSubscriptionStatus = "unpaid"
)

// Defines values for BillingStatusPlanTier.
const (
	BillingStatusPlanTierEnterprise BillingStatusPlanTier = "enterprise"
	BillingStatusPlanTierFree       BillingStatusPlanTier = "free"
	BillingStatusPlanTierPro        BillingStatusPlanTier = "pro"
	BillingStatusPlanTierStarter    BillingStatusPlanTier = "starter"
)

// Defines values for BillingStatusSubscriptionStatus.
const (
	BillingStatusSubscriptionStatusActive     BillingStatusSubscriptionStatus = "active"
	BillingStatusSubscriptionStatusCanceled   BillingStatusSubscriptionStatus = "canceled"
	BillingStatusSubscriptionStatusIncomplete BillingStatusSubscriptionStatus = "incomplete"
	BillingStatusSubscriptionStatusPastDue    BillingStatusSubscriptionStatus = "past_due"
	BillingStatusSubscriptionStatusTrialing   BillingStatusSubscriptionStatus = "trialing"
)

// Defines values for CompleteSignupResponseTokenType.
const (
	CompleteSignupResponseTokenTypeBearer CompleteSignupResponseTokenType = "Bearer"
)

// Defines values for CreateOutgoingWebhookRequestEvents.
const (
	CreateOutgoingWebhookRequestEventsJobCancelled       CreateOutgoingWebhookRequestEvents = "job.cancelled"
	CreateOutgoingWebhookRequestEventsJobCompleted       CreateOutgoingWebhookRequestEvents = "job.completed"
	CreateOutgoingWebhookRequestEventsJobCreated         CreateOutgoingWebhookRequestEvents = "job.created"
	CreateOutgoingWebhookRequestEventsJobFailed          CreateOutgoingWebhookRequestEvents = "job.failed"
	CreateOutgoingWebhookRequestEventsJobStarted         CreateOutgoingWebhookRequestEvents = "job.started"
	CreateOutgoingWebhookRequestEventsQueuePaused        CreateOutgoingWebhookRequestEvents = "queue.paused"
	CreateOutgoingWebhookRequestEventsQueueResumed       CreateOutgoingWebhookRequestEvents = "queue.resumed"
	CreateOutgoingWebhookRequestEventsScheduleTriggered  CreateOutgoingWebhookRequestEvents = "schedule.triggered"
	CreateOutgoingWebhookRequestEventsWorkerDeregistered CreateOutgoingWebhookRequestEvents = "worker.deregistered"
	CreateOutgoingWebhookRequestEventsWorkerRegistered   CreateOutgoingWebhookRequestEvents = "worker.registered"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusDegraded HealthResponseStatus = "degraded"
	HealthResponseStatusHealthy  HealthResponseStatus = "healthy"
)

// Defines values for JobStatus.
const (
	JobStatusCancelled  JobStatus = "cancelled"
	JobStatusCompleted  JobStatus = "completed"
	JobStatusDeadletter JobStatus = "deadletter"
	JobStatusFailed     JobStatus = "failed"
	JobStatusPending    JobStatus = "pending"
	JobStatusProcessing JobStatus = "processing"
	JobStatusScheduled  JobStatus = "scheduled"
)

// Defines values for LoginResponseTokenType.
const (
	LoginResponseTokenTypeBearer LoginResponseTokenType = "Bearer"
)

// Defines values for OrganizationPlanTier.
const (
	OrganizationPlanTierEnterprise OrganizationPlanTier = "enterprise"
	OrganizationPlanTierFree       OrganizationPlanTier = "free"
	OrganizationPlanTierPro        OrganizationPlanTier = "pro"
	OrganizationPlanTierStarter    OrganizationPlanTier = "starter"
)

// Defines values for OutgoingWebhookEvents.
const (
	OutgoingWebhookEventsJobCancelled       OutgoingWebhookEvents = "job.cancelled"
	OutgoingWebhookEventsJobCompleted       OutgoingWebhookEvents = "job.completed"
	OutgoingWebhookEventsJobCreated         OutgoingWebhookEvents = "job.created"
	OutgoingWebhookEventsJobFailed          OutgoingWebhookEvents = "job.failed"
	OutgoingWebhookEventsJobStarted         OutgoingWebhookEvents = "job.started"
	OutgoingWebhookEventsQueuePaused        OutgoingWebhookEvents = "queue.paused"
	OutgoingWebhookEventsQueueResumed       OutgoingWebhookEvents = "queue.resumed"
	OutgoingWebhookEventsScheduleTriggered  OutgoingWebhookEvents = "schedule.triggered"
	OutgoingWebhookEventsWorkerDeregistered OutgoingWebhookEvents = "worker.deregistered"
	OutgoingWebhookEventsWorkerRegistered   OutgoingWebhookEvents = "worker.registered"
)

// Defines values for OutgoingWebhookLastStatus.
const (
	OutgoingWebhookLastStatusFailed  OutgoingWebhookLastStatus = "failed"
	OutgoingWebhookLastStatusSuccess OutgoingWebhookLastStatus = "success"
)

// Defines values for OutgoingWebhookDeliveryStatus.
const (
	OutgoingWebhookDeliveryStatusFailed  OutgoingWebhookDeliveryStatus = "failed"
	OutgoingWebhookDeliveryStatusPending OutgoingWebhookDeliveryStatus = "pending"
	OutgoingWebhookDeliveryStatusSuccess OutgoingWebhookDeliveryStatus = "success"
)

// Defines values for RealtimeEventType.
const (
	RealtimeEventTypeError              RealtimeEventType = "error"
	RealtimeEventTypeJobCompleted       RealtimeEventType = "job.completed"
	RealtimeEventTypeJobCreated         RealtimeEventType = "job.created"
	RealtimeEventTypeJobFailed          RealtimeEventType = "job.failed"
	RealtimeEventTypeJobStatus          RealtimeEventType = "job.status"
	RealtimeEventTypePing               RealtimeEventType = "ping"
	RealtimeEventTypeQueueStats         RealtimeEventType = "queue.stats"
	RealtimeEventTypeSystemHealth       RealtimeEventType = "system.health"
	RealtimeEventTypeWorkerDeregistered RealtimeEventType = "worker.deregistered"
	RealtimeEventTypeWorkerHeartbeat    RealtimeEventType = "worker.heartbeat"
	RealtimeEventTypeWorkerRegistered   RealtimeEventType = "worker.registered"
)

// Defines values for RefreshTokenResponseTokenType.
const (
	RefreshTokenResponseTokenTypeBearer RefreshTokenResponseTokenType = "Bearer"
)

// Defines values for ScheduleRunStatus.
const (
	ScheduleRunStatusCompleted ScheduleRunStatus = "completed"
	ScheduleRunStatusFailed    ScheduleRunStatus = "failed"
	ScheduleRunStatusPending   ScheduleRunStatus = "pending"
	ScheduleRunStatusRunning   ScheduleRunStatus = "running"
)

// Defines values for UsageInfoPlan.
const (
	UsageInfoPlanEnterprise UsageInfoPlan = "enterprise"
	UsageInfoPlanFree       UsageInfoPlan = "free"
	UsageInfoPlanPro        UsageInfoPlan = "pro"
	UsageInfoPlanStarter    UsageInfoPlan = "starter"
)

// Defines values for UsageWarningSeverity.
const (
	Critical UsageWarningSeverity = "critical"
	Warning  UsageWarningSeverity = "warning"
)

// Defines values for VerifyEmailLoginResponseTokenType.
const (
	VerifyEmailLoginResponseTokenTypeBearer VerifyEmailLoginResponseTokenType = "Bearer"
)

// Defines values for VerifyEmailLoginResponseType.
const (
	Login VerifyEmailLoginResponseType = "login"
)

// Defines values for VerifyEmailSignupResponseType.
const (
	Signup VerifyEmailSignupResponseType = "signup"
)

// Defines values for WorkerStatus.
const (
	WorkerStatusDegraded WorkerStatus = "degraded"
	WorkerStatusDraining WorkerStatus = "draining"
	WorkerStatusHealthy  WorkerStatus = "healthy"
	WorkerStatusOffline  WorkerStatus = "offline"
)

// Defines values for WorkflowJobDefinitionDependencyMode.
const (
	WorkflowJobDefinitionDependencyModeAll WorkflowJobDefinitionDependencyMode = "all"
	WorkflowJobDefinitionDependencyModeAny WorkflowJobDefinitionDependencyMode = "any"
)

// Defines values for WorkflowResponseStatus.
const (
	WorkflowResponseStatusCancelled WorkflowResponseStatus = "cancelled"
	WorkflowResponseStatusCompleted WorkflowResponseStatus = "completed"
	WorkflowResponseStatusFailed    WorkflowResponseStatus = "failed"
	WorkflowResponseStatusPending   WorkflowResponseStatus = "pending"
	WorkflowResponseStatusRunning   WorkflowResponseStatus = "running"
)

// Defines values for AdminListOrganizationsParamsPlanTier.
const (
	AdminListOrganizationsParamsPlanTierEnterprise AdminListOrganizationsParamsPlanTier = "enterprise"
	AdminListOrganizationsParamsPlanTierFree       AdminListOrganizationsParamsPlanTier = "free"
	AdminListOrganizationsParamsPlanTierPro        AdminListOrganizationsParamsPlanTier = "pro"
	AdminListOrganizationsParamsPlanTierStarter    AdminListOrganizationsParamsPlanTier = "starter"
)

// Defines values for ListJobsParamsStatus.
const (
	ListJobsParamsStatusCancelled  ListJobsParamsStatus = "cancelled"
	ListJobsParamsStatusCompleted  ListJobsParamsStatus = "completed"
	ListJobsParamsStatusDeadletter ListJobsParamsStatus = "deadletter"
	ListJobsParamsStatusFailed     ListJobsParamsStatus = "failed"
	ListJobsParamsStatusPending    ListJobsParamsStatus = "pending"
	ListJobsParamsStatusProcessing ListJobsParamsStatus = "processing"
	ListJobsParamsStatusScheduled  ListJobsParamsStatus = "scheduled"
)

// Defines values for ListWorkflowsParamsStatus.
const (
	Cancelled ListWorkflowsParamsStatus = "cancelled"
	Completed ListWorkflowsParamsStatus = "completed"
	Failed    ListWorkflowsParamsStatus = "failed"
	Pending   ListWorkflowsParamsStatus = "pending"
	Running   ListWorkflowsParamsStatus = "running"
)

// AddDependenciesRequest defines model for AddDependenciesRequest.
type AddDependenciesRequest struct {
	DependencyMode *AddDependenciesRequestDependencyMode `json:"dependency_mode,omitempty"`
	DependsOn      []string                              `json:"depends_on"`
}

// AddDependenciesRequestDependencyMode defines model for AddDependenciesRequest.DependencyMode.
type AddDependenciesRequestDependencyMode string

// AddDependenciesResponse defines model for AddDependenciesResponse.
type AddDependenciesResponse struct {
	DependenciesAdded int  `json:"dependencies_added"`
	DependenciesMet   bool `json:"dependencies_met"`
}

// AdminCreateOrganizationRequest defines model for AdminCreateOrganizationRequest.
type AdminCreateOrganizationRequest struct {
	BillingEmail *openapi_types.Email                    `json:"billing_email,omitempty"`
	Name         string                                  `json:"name"`
	PlanTier     *AdminCreateOrganizationRequestPlanTier `json:"plan_tier,omitempty"`
	Settings     *map[string]interface{}                 `json:"settings,omitempty"`
	Slug         string                                  `json:"slug"`
}

// AdminCreateOrganizationRequestPlanTier defines model for AdminCreateOrganizationRequest.PlanTier.
type AdminCreateOrganizationRequestPlanTier string

// AdminCreateOrganizationResponse defines model for AdminCreateOrganizationResponse.
type AdminCreateOrganizationResponse struct {
	// ApiKey Initial API key (shown only once)
	ApiKey    string     `json:"api_key"`
	ApiKeyId  *string    `json:"api_key_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	PlanTier  string     `json:"plan_tier"`
	Slug      string     `json:"slug"`
}

// AdminOrganizationDetail defines model for AdminOrganizationDetail.
type AdminOrganizationDetail struct {
	BillingEmail   *string    `json:"billing_email,omitempty"`
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Id             *string    `json:"id,omitempty"`
	IsActive       *bool      `json:"is_active,omitempty"`
	Name           *string    `json:"name,omitempty"`
	PlanTier       *string    `json:"plan_tier,omitempty"`
	ResourceCounts *struct {
		ApiKeys   *int `json:"api_keys,omitempty"`
		Queues    *int `json:"queues,omitempty"`
		Schedules *int `json:"schedules,omitempty"`
		Webhooks  *int `json:"webhooks,omitempty"`
		Workers   *int `json:"workers,omitempty"`
		Workflows *int `json:"workflows,omitempty"`
	} `json:"resource_counts,omitempty"`
	Settings *map[string]interface{} `json:"settings,omitempty"`
	Slug     *string                 `json:"slug,omitempty"`

	// StripeCancelAtPeriodEnd Whether subscription will cancel at period end
	StripeCancelAtPeriodEnd *bool `json:"stripe_cancel_at_period_end"`

	// StripeCurrentPeriodEnd Current billing period end date
	StripeCurrentPeriodEnd *time.Time `json:"stripe_current_period_end"`

	// StripeCustomerId Stripe customer ID linked to this organization
	StripeCustomerId *string `json:"stripe_customer_id"`

	// StripeSubscriptionId Stripe subscription ID for billing
	StripeSubscriptionId *string `json:"stripe_subscription_id"`

	// StripeSubscriptionStatus Stripe subscription status (active, past_due, canceled, etc.)
	StripeSubscriptionStatus *string        `json:"stripe_subscription_status"`
	UpdatedAt                *time.Time     `json:"updated_at,omitempty"`
	Usage                    *ResourceUsage `json:"usage,omitempty"`
}

// AdminOrganizationList defines model for AdminOrganizationList.
type AdminOrganizationList struct {
	Limit         int                        `json:"limit"`
	Offset        int                        `json:"offset"`
	Organizations []AdminOrganizationSummary `json:"organizations"`
	Total         int                        `json:"total"`
}

// AdminOrganizationSummary defines model for AdminOrganizationSummary.
type AdminOrganizationSummary struct {
	ActiveJobs *int       `json:"active_jobs,omitempty"`
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	Id         *string    `json:"id,omitempty"`
	IsActive   *bool      `json:"is_active,omitempty"`
	JobsToday  *int       `json:"jobs_today,omitempty"`
	Name       *string    `json:"name,omitempty"`
	PlanTier   *string    `json:"plan_tier,omitempty"`
	Slug       *string    `json:"slug,omitempty"`
}

// AdminUpdateOrganizationRequest Update organization settings. All fields are optional.
//
// When setting `stripe_subscription_id`, the backend will auto-reconcile with Stripe API
// to fetch the correct plan tier, subscription status, and billing period from Stripe.
type AdminUpdateOrganizationRequest struct {
	BillingEmail *openapi_types.Email `json:"billing_email,omitempty"`

	// CustomLimits Custom limit overrides (null or empty object resets to plan defaults)
	CustomLimits *map[string]interface{}                 `json:"custom_limits"`
	IsActive     *bool                                   `json:"is_active,omitempty"`
	Name         *string                                 `json:"name,omitempty"`
	PlanTier     *AdminUpdateOrganizationRequestPlanTier `json:"plan_tier,omitempty"`
	Settings     *map[string]interface{}                 `json:"settings,omitempty"`

	// StripeCustomerId Link a Stripe customer to this organization
	StripeCustomerId *string `json:"stripe_customer_id"`

	// StripeSubscriptionId Link a Stripe subscription (triggers auto-reconciliation with Stripe)
	StripeSubscriptionId *string `json:"stripe_subscription_id"`

	// StripeSubscriptionStatus Subscription status (usually auto-filled by reconciliation)
	StripeSubscriptionStatus *AdminUpdateOrganizationRequestStripeSubscriptionStatus `json:"stripe_subscription_status"`
}

// AdminUpdateOrganizationRequestPlanTier defines model for AdminUpdateOrganizationRequest.PlanTier.
type AdminUpdateOrganizationRequestPlanTier string

// AdminUpdateOrganizationRequestStripeSubscriptionStatus Subscription status (usually auto-filled by reconciliation)
type AdminUpdateOrganizationRequestStripeSubscriptionStatus string

// ApiKeySummary defines model for ApiKeySummary.
type ApiKeySummary struct {
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id        string     `json:"id"`
	IsActive  bool       `json:"is_active"`
	LastUsed  *time.Time `json:"last_used,omitempty"`
	Name      string     `json:"name"`
	Queues    []string   `json:"queues"`
	RateLimit *int       `json:"rate_limit,omitempty"`
}

// BatchJobStatus defines model for BatchJobStatus.
type BatchJobStatus struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Id          string     `json:"id"`
	QueueName   string     `json:"queue_name"`
	RetryCount  int        `json:"retry_count"`
	Status      string     `json:"status"`
}

// BillingStatus defines model for BillingStatus.
type BillingStatus struct {
	CancelAtPeriodEnd  *bool                            `json:"cancel_at_period_end,omitempty"`
	CurrentPeriodEnd   *time.Time                       `json:"current_period_end,omitempty"`
	HasStripeCustomer  *bool                            `json:"has_stripe_customer,omitempty"`
	PlanTier           BillingStatusPlanTier            `json:"plan_tier"`
	StripeCustomerId   *string                          `json:"stripe_customer_id,omitempty"`
	SubscriptionStatus *BillingStatusSubscriptionStatus `json:"subscription_status,omitempty"`
}

// BillingStatusPlanTier defines model for BillingStatus.PlanTier.
type BillingStatusPlanTier string

// BillingStatusSubscriptionStatus defines model for BillingStatus.SubscriptionStatus.
type BillingStatusSubscriptionStatus string

// BoostPriorityRequest defines model for BoostPriorityRequest.
type BoostPriorityRequest struct {
	Priority int `json:"priority"`
}

// BoostPriorityResponse defines model for BoostPriorityResponse.
type BoostPriorityResponse struct {
	JobId       string `json:"job_id"`
	NewPriority int    `json:"new_priority"`
	OldPriority int    `json:"old_priority"`
}

// BulkEnqueueRequest defines model for BulkEnqueueRequest.
type BulkEnqueueRequest struct {
	DefaultMaxRetries     *int          `json:"default_max_retries,omitempty"`
	DefaultPriority       *int          `json:"default_priority,omitempty"`
	DefaultTimeoutSeconds *int          `json:"default_timeout_seconds,omitempty"`
	Jobs                  []BulkJobItem `json:"jobs"`
	QueueName             string        `json:"queue_name"`
}

// BulkEnqueueResponse defines model for BulkEnqueueResponse.
type BulkEnqueueResponse struct {
	Failed       []BulkJobError  `json:"failed"`
	FailureCount int             `json:"failure_count"`
	Succeeded    []BulkJobResult `json:"succeeded"`
	SuccessCount int             `json:"success_count"`
	Total        int             `json:"total"`
}

// BulkJobError defines model for BulkJobError.
type BulkJobError struct {
	Error string `json:"error"`
	Index int    `json:"index"`
}

// BulkJobItem defines model for BulkJobItem.
type BulkJobItem struct {
	IdempotencyKey *string                `json:"idempotency_key,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	Priority       *int                   `json:"priority,omitempty"`
	ScheduledAt    *time.Time             `json:"scheduled_at,omitempty"`
}

// BulkJobResult defines model for BulkJobResult.
type BulkJobResult struct {
	Created bool   `json:"created"`
	Index   int    `json:"index"`
	JobId   string `json:"job_id"`
}

// CheckEmailResponse defines model for CheckEmailResponse.
type CheckEmailResponse struct {
	// Available Whether the email is available (no account exists)
	Available bool `json:"available"`

	// Exists Whether an account exists with this email
	Exists bool `json:"exists"`
}

// CheckSlugResponse defines model for CheckSlugResponse.
type CheckSlugResponse struct {
	Available bool `json:"available"`

	// Suggestion Suggested alternative if not available
	Suggestion *string `json:"suggestion,omitempty"`
	Valid      bool    `json:"valid"`
}

// ClaimJobsRequest defines model for ClaimJobsRequest.
type ClaimJobsRequest struct {
	// LeaseDurationSecs Lease duration in seconds
	LeaseDurationSecs *int `json:"lease_duration_secs,omitempty"`

	// Limit Maximum number of jobs to claim
	Limit *int `json:"limit,omitempty"`

	// QueueName Queue to claim jobs from
	QueueName string `json:"queue_name"`

	// WorkerId Worker identifier (for tracking)
	WorkerId *string `json:"worker_id,omitempty"`
}

// ClaimJobsResponse defines model for ClaimJobsResponse.
type ClaimJobsResponse struct {
	Jobs []ClaimedJob `json:"jobs"`
}

// ClaimedJob defines model for ClaimedJob.
type ClaimedJob struct {
	CreatedAt      *time.Time             `json:"created_at,omitempty"`
	Id             string                 `json:"id"`
	LeaseExpiresAt time.Time              `json:"lease_expires_at"`
	MaxRetries     *int                   `json:"max_retries,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	Priority       *int                   `json:"priority,omitempty"`
	QueueName      string                 `json:"queue_name"`
	RetryCount     *int                   `json:"retry_count,omitempty"`
	Status         string                 `json:"status"`
	TimeoutSeconds *int                   `json:"timeout_seconds,omitempty"`
}

// CompleteJobRequest defines model for CompleteJobRequest.
type CompleteJobRequest struct {
	// Result Optional result data to store with the job
	Result   *map[string]interface{} `json:"result,omitempty"`
	WorkerId *string                 `json:"worker_id,omitempty"`
}

// CompleteSignupRequest defines model for CompleteSignupRequest.
type CompleteSignupRequest struct {
	Name        string `json:"name"`
	SignupToken string `json:"signup_token"`
	Slug        string `json:"slug"`
}

// CompleteSignupResponse defines model for CompleteSignupResponse.
type CompleteSignupResponse struct {
	AccessToken string `json:"access_token"`

	// ApiKey Initial API key (shown only once)
	ApiKey       string                          `json:"api_key"`
	ExpiresIn    int                             `json:"expires_in"`
	Organization SignupOrganization              `json:"organization"`
	RefreshToken string                          `json:"refresh_token"`
	TokenType    CompleteSignupResponseTokenType `json:"token_type"`
}

// CompleteSignupResponseTokenType defines model for CompleteSignupResponse.TokenType.
type CompleteSignupResponseTokenType string

// CreateApiKeyRequest defines model for CreateApiKeyRequest.
type CreateApiKeyRequest struct {
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Name      string     `json:"name"`
	Queues    *[]string  `json:"queues,omitempty"`
	RateLimit *int       `json:"rate_limit,omitempty"`
}

// CreateApiKeyResponse defines model for CreateApiKeyResponse.
type CreateApiKeyResponse struct {
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id        string     `json:"id"`

	// Key The raw API key (only shown once)
	Key  string `json:"key"`
	Name string `json:"name"`
}

// CreateJobRequest defines model for CreateJobRequest.
type CreateJobRequest struct {
	CompletionWebhook *string                 `json:"completion_webhook,omitempty"`
	ExpiresAt         *time.Time              `json:"expires_at,omitempty"`
	IdempotencyKey    *string                 `json:"idempotency_key,omitempty"`
	MaxRetries        *int                    `json:"max_retries,omitempty"`
	ParentJobId       *string                 `json:"parent_job_id,omitempty"`
	Payload           map[string]interface{}  `json:"payload"`
	Priority          *int                    `json:"priority,omitempty"`
	QueueName         string                  `json:"queue_name"`
	ScheduledAt       *time.Time              `json:"scheduled_at,omitempty"`
	Tags              *map[string]interface{} `json:"tags,omitempty"`
	TimeoutSeconds    *int                    `json:"timeout_seconds,omitempty"`
}

// CreateJobResponse defines model for CreateJobResponse.
type CreateJobResponse struct {
	// Created Whether this was a new job or existing
	Created bool `json:"created"`

	// Id Job ID (new or existing if idempotent)
	Id string `json:"id"`
}

// CreateOrganizationRequest defines model for CreateOrganizationRequest.
type CreateOrganizationRequest struct {
	BillingEmail *openapi_types.Email `json:"billing_email,omitempty"`
	Name         string               `json:"name"`
	Slug         string               `json:"slug"`
}

// CreateOutgoingWebhookRequest defines model for CreateOutgoingWebhookRequest.
type CreateOutgoingWebhookRequest struct {
	Enabled *bool                                `json:"enabled,omitempty"`
	Events  []CreateOutgoingWebhookRequestEvents `json:"events"`
	Name    string                               `json:"name"`

	// Secret Optional HMAC secret for signing webhook payloads
	Secret *string `json:"secret,omitempty"`
	Url    string  `json:"url"`
}

// CreateOutgoingWebhookRequestEvents defines model for CreateOutgoingWebhookRequest.Events.
type CreateOutgoingWebhookRequestEvents string

// CreatePortalRequest defines model for CreatePortalRequest.
type CreatePortalRequest struct {
	ReturnUrl string `json:"return_url"`
}

// CreatePortalResponse defines model for CreatePortalResponse.
type CreatePortalResponse struct {
	// Url Stripe Customer Portal URL
	Url string `json:"url"`
}

// CreateScheduleRequest defines model for CreateScheduleRequest.
type CreateScheduleRequest struct {
	// CronExpression 6-field cron expression
	CronExpression  string                  `json:"cron_expression"`
	Description     *string                 `json:"description,omitempty"`
	MaxRetries      *int                    `json:"max_retries,omitempty"`
	Metadata        *map[string]interface{} `json:"metadata,omitempty"`
	Name            string                  `json:"name"`
	PayloadTemplate map[string]interface{}  `json:"payload_template"`
	Priority        *int                    `json:"priority,omitempty"`
	QueueName       string                  `json:"queue_name"`
	Tags            *map[string]interface{} `json:"tags,omitempty"`
	TimeoutSeconds  *int                    `json:"timeout_seconds,omitempty"`
	Timezone        *string                 `json:"timezone,omitempty"`
}

// CreateScheduleResponse defines model for CreateScheduleResponse.
type CreateScheduleResponse struct {
	CronExpression string     `json:"cron_expression"`
	Id             string     `json:"id"`
	Name           string     `json:"name"`
	NextRunAt      *time.Time `json:"next_run_at,omitempty"`
}

// CreateWorkflowRequest defines model for CreateWorkflowRequest.
type CreateWorkflowRequest struct {
	Description *string                 `json:"description,omitempty"`
	Jobs        []WorkflowJobDefinition `json:"jobs"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Name        string                  `json:"name"`
}

// CreateWorkflowResponse defines model for CreateWorkflowResponse.
type CreateWorkflowResponse struct {
	JobIds     []WorkflowJobMapping `json:"job_ids"`
	Status     string               `json:"status"`
	WorkflowId openapi_types.UUID   `json:"workflow_id"`
}

// CurrentUserResponse defines model for CurrentUserResponse.
type CurrentUserResponse struct {
	ApiKeyId       string    `json:"api_key_id"`
	ExpiresAt      time.Time `json:"expires_at"`
	IssuedAt       time.Time `json:"issued_at"`
	OrganizationId string    `json:"organization_id"`
	Queues         []string  `json:"queues"`
}

// CustomWebhookRequest defines model for CustomWebhookRequest.
type CustomWebhookRequest struct {
	EventType      *string                `json:"event_type,omitempty"`
	IdempotencyKey *string                `json:"idempotency_key,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	Priority       *int                   `json:"priority,omitempty"`
	QueueName      string                 `json:"queue_name"`
}

// DashboardData defines model for DashboardData.
type DashboardData struct {
	Jobs           JobSummaryStats     `json:"jobs"`
	Queues         []QueueSummary      `json:"queues"`
	RecentActivity RecentActivity      `json:"recent_activity"`
	System         SystemInfo          `json:"system"`
	Workers        WorkerHealthSummary `json:"workers"`
}

// DependencyInfo defines model for DependencyInfo.
type DependencyInfo struct {
	JobId     string `json:"job_id"`
	QueueName string `json:"queue_name"`
	Status    string `json:"status"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error code
	Code string `json:"code"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// FailJobRequest defines model for FailJobRequest.
type FailJobRequest struct {
	// NoRetry Skip retries and go directly to DLQ
	NoRetry *bool `json:"no_retry,omitempty"`

	// Reason Reason for failure
	Reason   string  `json:"reason"`
	WorkerId *string `json:"worker_id,omitempty"`
}

// GenerateSlugRequest defines model for GenerateSlugRequest.
type GenerateSlugRequest struct {
	Name string `json:"name"`
}

// GenerateSlugResponse defines model for GenerateSlugResponse.
type GenerateSlugResponse struct {
	Slug string `json:"slug"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Cache    bool                 `json:"cache"`
	Database bool                 `json:"database"`
	Status   HealthResponseStatus `json:"status"`
	Version  string               `json:"version"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// HeartbeatJobRequest defines model for HeartbeatJobRequest.
type HeartbeatJobRequest struct {
	// ExtensionSecs Extend lease by this many seconds
	ExtensionSecs *int    `json:"extension_secs,omitempty"`
	WorkerId      *string `json:"worker_id,omitempty"`
}

// Job defines model for Job.
type Job struct {
	AssignedWorkerId  *string                 `json:"assigned_worker_id,omitempty"`
	CompletedAt       *time.Time              `json:"completed_at,omitempty"`
	CompletionWebhook *string                 `json:"completion_webhook,omitempty"`
	CreatedAt         time.Time               `json:"created_at"`
	ExpiresAt         *time.Time              `json:"expires_at,omitempty"`
	Id                string                  `json:"id"`
	IdempotencyKey    *string                 `json:"idempotency_key,omitempty"`
	LastError         *string                 `json:"last_error,omitempty"`
	LeaseExpiresAt    *time.Time              `json:"lease_expires_at,omitempty"`
	LeaseId           *string                 `json:"lease_id,omitempty"`
	MaxRetries        int                     `json:"max_retries"`
	OrganizationId    string                  `json:"organization_id"`
	ParentJobId       *string                 `json:"parent_job_id,omitempty"`
	Payload           map[string]interface{}  `json:"payload"`
	Priority          int                     `json:"priority"`
	QueueName         string                  `json:"queue_name"`
	Result            *map[string]interface{} `json:"result,omitempty"`
	RetryCount        int                     `json:"retry_count"`
	ScheduledAt       *time.Time              `json:"scheduled_at,omitempty"`
	StartedAt         *time.Time              `json:"started_at,omitempty"`
	Status            JobStatus               `json:"status"`
	Tags              *map[string]interface{} `json:"tags,omitempty"`
	TimeoutSeconds    int                     `json:"timeout_seconds"`
	UpdatedAt         time.Time               `json:"updated_at"`
}

// JobStatus defines model for Job.Status.
type JobStatus string

// JobStats defines model for JobStats.
type JobStats struct {
	Cancelled  int `json:"cancelled"`
	Completed  int `json:"completed"`
	Deadletter int `json:"deadletter"`
	Failed     int `json:"failed"`
	Pending    int `json:"pending"`
	Processing int `json:"processing"`
	Scheduled  int `json:"scheduled"`
	Total      int `json:"total"`
}

// JobSummary defines model for JobSummary.
type JobSummary struct {
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Id          string     `json:"id"`
	Priority    int        `json:"priority"`
	QueueName   string     `json:"queue_name"`
	RetryCount  int        `json:"retry_count"`
	ScheduledAt *time.Time `json:"scheduled_at,omitempty"`
	StartedAt   *time.Time `json:"started_at,omitempty"`
	Status      string     `json:"status"`
}

// JobSummaryStats defines model for JobSummaryStats.
type JobSummaryStats struct {
	AvgProcessingTimeMs *float32 `json:"avg_processing_time_ms,omitempty"`
	AvgWaitTimeMs       *float32 `json:"avg_wait_time_ms,omitempty"`
	Completed24h        int      `json:"completed_24h"`
	Deadletter          int      `json:"deadletter"`
	Failed24h           int      `json:"failed_24h"`
	Pending             int      `json:"pending"`
	Processing          int      `json:"processing"`
	Total               int      `json:"total"`
}

// JobWithDependencies defines model for JobWithDependencies.
type JobWithDependencies struct {
	Dependencies    []DependencyInfo `json:"dependencies"`
	DependenciesMet bool             `json:"dependencies_met"`
	Dependents      []DependencyInfo `json:"dependents"`
	JobId           string           `json:"job_id"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// ApiKey API key to exchange for JWT tokens
	ApiKey string `json:"api_key"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// AccessToken JWT access token (short-lived)
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token expiration in seconds
	ExpiresIn int `json:"expires_in"`

	// RefreshExpiresIn Refresh token expiration in seconds
	RefreshExpiresIn int `json:"refresh_expires_in"`

	// RefreshToken JWT refresh token (long-lived)
	RefreshToken string                 `json:"refresh_token"`
	TokenType    LoginResponseTokenType `json:"token_type"`
}

// LoginResponseTokenType defines model for LoginResponse.TokenType.
type LoginResponseTokenType string

// Organization defines model for Organization.
type Organization struct {
	BillingEmail *openapi_types.Email   `json:"billing_email,omitempty"`
	CreatedAt    time.Time              `json:"created_at"`
	Id           string                 `json:"id"`
	Name         string                 `json:"name"`
	PlanTier     OrganizationPlanTier   `json:"plan_tier"`
	Settings     map[string]interface{} `json:"settings"`
	Slug         string                 `json:"slug"`
	UpdatedAt    time.Time              `json:"updated_at"`
}

// OrganizationPlanTier defines model for Organization.PlanTier.
type OrganizationPlanTier string

// OrganizationSummary defines model for OrganizationSummary.
type OrganizationSummary struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Name      string    `json:"name"`
	PlanTier  string    `json:"plan_tier"`
	Slug      string    `json:"slug"`
}

// OutgoingWebhook defines model for OutgoingWebhook.
type OutgoingWebhook struct {
	CreatedAt       time.Time                  `json:"created_at"`
	Enabled         bool                       `json:"enabled"`
	Events          []OutgoingWebhookEvents    `json:"events"`
	FailureCount    int                        `json:"failure_count"`
	Id              string                     `json:"id"`
	LastStatus      *OutgoingWebhookLastStatus `json:"last_status,omitempty"`
	LastTriggeredAt *time.Time                 `json:"last_triggered_at,omitempty"`
	Name            string                     `json:"name"`
	OrganizationId  string                     `json:"organization_id"`
	UpdatedAt       time.Time                  `json:"updated_at"`
	Url             string                     `json:"url"`
}

// OutgoingWebhookEvents defines model for OutgoingWebhook.Events.
type OutgoingWebhookEvents string

// OutgoingWebhookLastStatus defines model for OutgoingWebhook.LastStatus.
type OutgoingWebhookLastStatus string

// OutgoingWebhookDelivery defines model for OutgoingWebhookDelivery.
type OutgoingWebhookDelivery struct {
	Attempts     int                           `json:"attempts"`
	CreatedAt    time.Time                     `json:"created_at"`
	DeliveredAt  *time.Time                    `json:"delivered_at,omitempty"`
	Error        *string                       `json:"error,omitempty"`
	Event        string                        `json:"event"`
	Id           string                        `json:"id"`
	Payload      map[string]interface{}        `json:"payload"`
	ResponseBody *string                       `json:"response_body,omitempty"`
	Status       OutgoingWebhookDeliveryStatus `json:"status"`
	StatusCode   *int                          `json:"status_code,omitempty"`
	WebhookId    string                        `json:"webhook_id"`
}

// OutgoingWebhookDeliveryStatus defines model for OutgoingWebhookDelivery.Status.
type OutgoingWebhookDeliveryStatus string

// PauseQueueRequest defines model for PauseQueueRequest.
type PauseQueueRequest struct {
	// Reason Optional reason for pausing
	Reason *string `json:"reason,omitempty"`
}

// PauseQueueResponse defines model for PauseQueueResponse.
type PauseQueueResponse struct {
	Paused    bool      `json:"paused"`
	PausedAt  time.Time `json:"paused_at"`
	QueueName string    `json:"queue_name"`
	Reason    *string   `json:"reason,omitempty"`
}

// PlanLimits defines model for PlanLimits.
type PlanLimits struct {
	DisplayName                *string `json:"display_name,omitempty"`
	HistoryRetentionDays       *int    `json:"history_retention_days,omitempty"`
	JobRetentionDays           *int    `json:"job_retention_days,omitempty"`
	MaxActiveJobs              *int    `json:"max_active_jobs"`
	MaxApiKeys                 *int    `json:"max_api_keys"`
	MaxJobsPerDay              *int    `json:"max_jobs_per_day"`
	MaxPayloadSizeBytes        *int    `json:"max_payload_size_bytes,omitempty"`
	MaxQueues                  *int    `json:"max_queues"`
	MaxSchedules               *int    `json:"max_schedules"`
	MaxWebhooks                *int    `json:"max_webhooks"`
	MaxWorkers                 *int    `json:"max_workers"`
	MaxWorkflows               *int    `json:"max_workflows"`
	RateLimitBurst             *int    `json:"rate_limit_burst,omitempty"`
	RateLimitRequestsPerSecond *int    `json:"rate_limit_requests_per_second,omitempty"`
	Tier                       *string `json:"tier,omitempty"`
}

// PlatformStats defines model for PlatformStats.
type PlatformStats struct {
	ActiveOrganizations *int            `json:"active_organizations,omitempty"`
	ActiveWorkers       *int            `json:"active_workers,omitempty"`
	CompletedJobs24h    *int            `json:"completed_jobs_24h,omitempty"`
	FailedJobs24h       *int            `json:"failed_jobs_24h,omitempty"`
	OrganizationsByPlan *map[string]int `json:"organizations_by_plan,omitempty"`
	TotalJobs24h        *int            `json:"total_jobs_24h,omitempty"`
	TotalOrganizations  *int            `json:"total_organizations,omitempty"`
}

// PurgeDlqRequest defines model for PurgeDlqRequest.
type PurgeDlqRequest struct {
	// Confirm Must be true to execute purge
	Confirm   bool       `json:"confirm"`
	OlderThan *time.Time `json:"older_than,omitempty"`
	QueueName *string    `json:"queue_name,omitempty"`
}

// PurgeDlqResponse defines model for PurgeDlqResponse.
type PurgeDlqResponse struct {
	PurgedCount int `json:"purged_count"`
}

// QueueConfig defines model for QueueConfig.
type QueueConfig struct {
	CreatedAt      time.Time              `json:"created_at"`
	DefaultTimeout int                    `json:"default_timeout"`
	Enabled        bool                   `json:"enabled"`
	Id             string                 `json:"id"`
	MaxRetries     int                    `json:"max_retries"`
	OrganizationId string                 `json:"organization_id"`
	QueueName      string                 `json:"queue_name"`
	RateLimit      *int                   `json:"rate_limit,omitempty"`
	Settings       map[string]interface{} `json:"settings"`
	UpdatedAt      time.Time              `json:"updated_at"`
}

// QueueConfigSummary defines model for QueueConfigSummary.
type QueueConfigSummary struct {
	DefaultTimeout int    `json:"default_timeout"`
	Enabled        bool   `json:"enabled"`
	MaxRetries     int    `json:"max_retries"`
	QueueName      string `json:"queue_name"`
	RateLimit      *int   `json:"rate_limit,omitempty"`
}

// QueueStats defines model for QueueStats.
type QueueStats struct {
	ActiveWorkers       int      `json:"active_workers"`
	AvgProcessingTimeMs *float32 `json:"avg_processing_time_ms,omitempty"`
	CompletedJobs24h    int      `json:"completed_jobs_24h"`
	FailedJobs24h       int      `json:"failed_jobs_24h"`
	MaxJobAgeSeconds    *int     `json:"max_job_age_seconds,omitempty"`
	PendingJobs         int      `json:"pending_jobs"`
	ProcessingJobs      int      `json:"processing_jobs"`
	QueueName           string   `json:"queue_name"`
}

// QueueSummary defines model for QueueSummary.
type QueueSummary struct {
	Name       string `json:"name"`
	Paused     bool   `json:"paused"`
	Pending    int    `json:"pending"`
	Processing int    `json:"processing"`
}

// RealtimeEvent defines model for RealtimeEvent.
type RealtimeEvent struct {
	Data map[string]interface{} `json:"data"`
	Type RealtimeEventType      `json:"type"`
}

// RealtimeEventType defines model for RealtimeEvent.Type.
type RealtimeEventType string

// RecentActivity defines model for RecentActivity.
type RecentActivity struct {
	JobsCompleted1h int `json:"jobs_completed_1h"`
	JobsCreated1h   int `json:"jobs_created_1h"`
	JobsFailed1h    int `json:"jobs_failed_1h"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken Valid refresh token
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenResponse defines model for RefreshTokenResponse.
type RefreshTokenResponse struct {
	// AccessToken New JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token expiration in seconds
	ExpiresIn int                           `json:"expires_in"`
	TokenType RefreshTokenResponseTokenType `json:"token_type"`
}

// RefreshTokenResponseTokenType defines model for RefreshTokenResponse.TokenType.
type RefreshTokenResponseTokenType string

// RegisterWorkerRequest defines model for RegisterWorkerRequest.
type RegisterWorkerRequest struct {
	Hostname       string                  `json:"hostname"`
	MaxConcurrency *int                    `json:"max_concurrency,omitempty"`
	Metadata       *map[string]interface{} `json:"metadata,omitempty"`
	QueueName      string                  `json:"queue_name"`
	Version        *string                 `json:"version,omitempty"`
	WorkerType     *string                 `json:"worker_type,omitempty"`
}

// RegisterWorkerResponse defines model for RegisterWorkerResponse.
type RegisterWorkerResponse struct {
	HeartbeatIntervalSecs int    `json:"heartbeat_interval_secs"`
	Id                    string `json:"id"`
	LeaseDurationSecs     int    `json:"lease_duration_secs"`
	QueueName             string `json:"queue_name"`
}

// ResourceUsage defines model for ResourceUsage.
type ResourceUsage struct {
	ActiveJobs *UsageItem `json:"active_jobs,omitempty"`
	ApiKeys    *UsageItem `json:"api_keys,omitempty"`
	JobsToday  *UsageItem `json:"jobs_today,omitempty"`
	Queues     *UsageItem `json:"queues,omitempty"`
	Schedules  *UsageItem `json:"schedules,omitempty"`
	Webhooks   *UsageItem `json:"webhooks,omitempty"`
	Workers    *UsageItem `json:"workers,omitempty"`
	Workflows  *UsageItem `json:"workflows,omitempty"`
}

// ResumeQueueResponse defines model for ResumeQueueResponse.
type ResumeQueueResponse struct {
	PausedDurationSecs int    `json:"paused_duration_secs"`
	QueueName          string `json:"queue_name"`
	Resumed            bool   `json:"resumed"`
}

// RetryDlqRequest defines model for RetryDlqRequest.
type RetryDlqRequest struct {
	JobIds    *[]string `json:"job_ids,omitempty"`
	Limit     *int      `json:"limit,omitempty"`
	QueueName *string   `json:"queue_name,omitempty"`
}

// RetryDlqResponse defines model for RetryDlqResponse.
type RetryDlqResponse struct {
	RetriedCount int      `json:"retried_count"`
	RetriedJobs  []string `json:"retried_jobs"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	CreatedAt time.Time `json:"created_at"`

	// CronExpression 6-field cron expression (second minute hour day month weekday)
	CronExpression  string                  `json:"cron_expression"`
	Description     *string                 `json:"description,omitempty"`
	Id              string                  `json:"id"`
	IsActive        bool                    `json:"is_active"`
	LastRunAt       *time.Time              `json:"last_run_at,omitempty"`
	MaxRetries      *int                    `json:"max_retries,omitempty"`
	Metadata        *map[string]interface{} `json:"metadata,omitempty"`
	Name            string                  `json:"name"`
	NextRunAt       *time.Time              `json:"next_run_at,omitempty"`
	OrganizationId  string                  `json:"organization_id"`
	PayloadTemplate *map[string]interface{} `json:"payload_template,omitempty"`
	Priority        *int                    `json:"priority,omitempty"`
	QueueName       string                  `json:"queue_name"`
	RunCount        *int                    `json:"run_count,omitempty"`
	Tags            *map[string]interface{} `json:"tags,omitempty"`
	TimeoutSeconds  *int                    `json:"timeout_seconds,omitempty"`
	Timezone        string                  `json:"timezone"`
	UpdatedAt       *time.Time              `json:"updated_at,omitempty"`
}

// ScheduleRun defines model for ScheduleRun.
type ScheduleRun struct {
	CompletedAt  *time.Time        `json:"completed_at,omitempty"`
	ErrorMessage *string           `json:"error_message,omitempty"`
	Id           string            `json:"id"`
	JobId        *string           `json:"job_id,omitempty"`
	ScheduleId   string            `json:"schedule_id"`
	StartedAt    time.Time         `json:"started_at"`
	Status       ScheduleRunStatus `json:"status"`
}

// ScheduleRunStatus defines model for ScheduleRun.Status.
type ScheduleRunStatus string

// SignupOrganization defines model for SignupOrganization.
type SignupOrganization struct {
	BillingEmail openapi_types.Email `json:"billing_email"`
	Id           string              `json:"id"`
	Name         string              `json:"name"`
	Slug         string              `json:"slug"`
}

// StartEmailLoginRequest defines model for StartEmailLoginRequest.
type StartEmailLoginRequest struct {
	Email openapi_types.Email `json:"email"`
}

// StartEmailLoginResponse defines model for StartEmailLoginResponse.
type StartEmailLoginResponse struct {
	// EmailSentTo Email address masked for privacy
	EmailSentTo string `json:"email_sent_to"`

	// Message Human-friendly status message
	Message string `json:"message"`
}

// SystemInfo defines model for SystemInfo.
type SystemInfo struct {
	CacheStatus    string    `json:"cache_status"`
	DatabaseStatus string    `json:"database_status"`
	Environment    string    `json:"environment"`
	StartedAt      time.Time `json:"started_at"`
	UptimeSeconds  int       `json:"uptime_seconds"`
	Version        string    `json:"version"`
}

// TestWebhookResponse defines model for TestWebhookResponse.
type TestWebhookResponse struct {
	Error          *string `json:"error,omitempty"`
	ResponseTimeMs int     `json:"response_time_ms"`
	StatusCode     *int    `json:"status_code,omitempty"`
	Success        bool    `json:"success"`
}

// TriggerScheduleResponse defines model for TriggerScheduleResponse.
type TriggerScheduleResponse struct {
	JobId       string    `json:"job_id"`
	TriggeredAt time.Time `json:"triggered_at"`
}

// UpdateApiKeyRequest defines model for UpdateApiKeyRequest.
type UpdateApiKeyRequest struct {
	IsActive  *bool     `json:"is_active,omitempty"`
	Name      *string   `json:"name,omitempty"`
	Queues    *[]string `json:"queues,omitempty"`
	RateLimit *int      `json:"rate_limit,omitempty"`
}

// UpdateOrganizationRequest defines model for UpdateOrganizationRequest.
type UpdateOrganizationRequest struct {
	BillingEmail *openapi_types.Email    `json:"billing_email,omitempty"`
	Name         *string                 `json:"name,omitempty"`
	Settings     *map[string]interface{} `json:"settings,omitempty"`
}

// UpdateOutgoingWebhookRequest defines model for UpdateOutgoingWebhookRequest.
type UpdateOutgoingWebhookRequest struct {
	Enabled *bool     `json:"enabled,omitempty"`
	Events  *[]string `json:"events,omitempty"`
	Name    *string   `json:"name,omitempty"`
	Secret  *string   `json:"secret,omitempty"`
	Url     *string   `json:"url,omitempty"`
}

// UpdateScheduleRequest defines model for UpdateScheduleRequest.
type UpdateScheduleRequest struct {
	CronExpression  *string                 `json:"cron_expression,omitempty"`
	Description     *string                 `json:"description,omitempty"`
	IsActive        *bool                   `json:"is_active,omitempty"`
	MaxRetries      *int                    `json:"max_retries,omitempty"`
	Metadata        *map[string]interface{} `json:"metadata,omitempty"`
	Name            *string                 `json:"name,omitempty"`
	PayloadTemplate *map[string]interface{} `json:"payload_template,omitempty"`
	Priority        *int                    `json:"priority,omitempty"`
	Tags            *map[string]interface{} `json:"tags,omitempty"`
	TimeoutSeconds  *int                    `json:"timeout_seconds,omitempty"`
	Timezone        *string                 `json:"timezone,omitempty"`
}

// UpsertQueueConfigRequest defines model for UpsertQueueConfigRequest.
type UpsertQueueConfigRequest struct {
	DefaultTimeout *int                    `json:"default_timeout,omitempty"`
	Enabled        *bool                   `json:"enabled,omitempty"`
	MaxRetries     *int                    `json:"max_retries,omitempty"`
	QueueName      string                  `json:"queue_name"`
	RateLimit      *int                    `json:"rate_limit,omitempty"`
	Settings       *map[string]interface{} `json:"settings,omitempty"`
}

// UsageInfo defines model for UsageInfo.
type UsageInfo struct {
	Limits   PlanLimits     `json:"limits"`
	Plan     UsageInfoPlan  `json:"plan"`
	Usage    ResourceUsage  `json:"usage"`
	Warnings []UsageWarning `json:"warnings"`
}

// UsageInfoPlan defines model for UsageInfo.Plan.
type UsageInfoPlan string

// UsageItem defines model for UsageItem.
type UsageItem struct {
	Current    *int     `json:"current,omitempty"`
	Limit      *int     `json:"limit"`
	Percentage *float32 `json:"percentage"`
}

// UsageWarning defines model for UsageWarning.
type UsageWarning struct {
	Current  *int                  `json:"current,omitempty"`
	Limit    *int                  `json:"limit,omitempty"`
	Message  *string               `json:"message,omitempty"`
	Resource *string               `json:"resource,omitempty"`
	Severity *UsageWarningSeverity `json:"severity,omitempty"`
}

// UsageWarningSeverity defines model for UsageWarning.Severity.
type UsageWarningSeverity string

// ValidateTokenRequest defines model for ValidateTokenRequest.
type ValidateTokenRequest struct {
	// Token JWT token to validate
	Token string `json:"token"`
}

// ValidateTokenResponse defines model for ValidateTokenResponse.
type ValidateTokenResponse struct {
	// Claims Token claims if valid
	Claims *map[string]interface{} `json:"claims,omitempty"`

	// Error Error message if token is invalid
	Error *string `json:"error,omitempty"`
	Valid bool    `json:"valid"`
}

// VerifyEmailLoginResponse defines model for VerifyEmailLoginResponse.
type VerifyEmailLoginResponse struct {
	AccessToken      string                            `json:"access_token"`
	ExpiresIn        int                               `json:"expires_in"`
	RefreshExpiresIn int                               `json:"refresh_expires_in"`
	RefreshToken     string                            `json:"refresh_token"`
	TokenType        VerifyEmailLoginResponseTokenType `json:"token_type"`
	Type             VerifyEmailLoginResponseType      `json:"type"`
}

// VerifyEmailLoginResponseTokenType defines model for VerifyEmailLoginResponse.TokenType.
type VerifyEmailLoginResponseTokenType string

// VerifyEmailLoginResponseType defines model for VerifyEmailLoginResponse.Type.
type VerifyEmailLoginResponseType string

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// VerifyEmailResponse Email verification result. The response is one of:
// - `type: login` (existing organization) with JWT tokens
// - `type: signup` (new email) with a short-lived signup token
type VerifyEmailResponse struct {
	union json.RawMessage
}

// VerifyEmailSignupResponse defines model for VerifyEmailSignupResponse.
type VerifyEmailSignupResponse struct {
	Email openapi_types.Email `json:"email"`

	// ExpiresIn Token expiration in seconds
	ExpiresIn int `json:"expires_in"`

	// SignupToken Token to complete signup (used with /api/v1/auth/signup/complete)
	SignupToken string                        `json:"signup_token"`
	Type        VerifyEmailSignupResponseType `json:"type"`
}

// VerifyEmailSignupResponseType defines model for VerifyEmailSignupResponse.Type.
type VerifyEmailSignupResponseType string

// WebhookResponse defines model for WebhookResponse.
type WebhookResponse struct {
	// JobId ID of the created job
	JobId *string `json:"job_id,omitempty"`

	// QueueName Name of the queue the job was enqueued to
	QueueName *string `json:"queue_name,omitempty"`

	// Status Job status (pending, scheduled)
	Status *string `json:"status,omitempty"`
}

// WebhookTokenResponse defines model for WebhookTokenResponse.
type WebhookTokenResponse struct {
	// WebhookToken The webhook token (null if cleared)
	WebhookToken *string `json:"webhook_token"`

	// WebhookUrl The webhook URL for this organization
	WebhookUrl string `json:"webhook_url"`
}

// Worker defines model for Worker.
type Worker struct {
	CurrentJobs    int                    `json:"current_jobs"`
	Hostname       string                 `json:"hostname"`
	Id             string                 `json:"id"`
	LastHeartbeat  time.Time              `json:"last_heartbeat"`
	MaxConcurrency int                    `json:"max_concurrency"`
	Metadata       map[string]interface{} `json:"metadata"`
	OrganizationId string                 `json:"organization_id"`
	QueueName      string                 `json:"queue_name"`
	RegisteredAt   time.Time              `json:"registered_at"`
	Status         WorkerStatus           `json:"status"`
	Version        *string                `json:"version,omitempty"`
	WorkerType     *string                `json:"worker_type,omitempty"`
}

// WorkerStatus defines model for Worker.Status.
type WorkerStatus string

// WorkerHealthSummary defines model for WorkerHealthSummary.
type WorkerHealthSummary struct {
	Healthy   int `json:"healthy"`
	Total     int `json:"total"`
	Unhealthy int `json:"unhealthy"`
}

// WorkerHeartbeatRequest defines model for WorkerHeartbeatRequest.
type WorkerHeartbeatRequest struct {
	CurrentJobs int                     `json:"current_jobs"`
	Metadata    *map[string]interface{} `json:"metadata,omitempty"`
	Status      *string                 `json:"status,omitempty"`
}

// WorkerSummary defines model for WorkerSummary.
type WorkerSummary struct {
	CurrentJobs    int       `json:"current_jobs"`
	Hostname       string    `json:"hostname"`
	Id             string    `json:"id"`
	LastHeartbeat  time.Time `json:"last_heartbeat"`
	MaxConcurrency int       `json:"max_concurrency"`
	QueueName      string    `json:"queue_name"`
	Status         string    `json:"status"`
}

// WorkflowJobDefinition defines model for WorkflowJobDefinition.
type WorkflowJobDefinition struct {
	DependencyMode *WorkflowJobDefinitionDependencyMode `json:"dependency_mode,omitempty"`

	// DependsOn Keys of jobs this job depends on
	DependsOn *[]string `json:"depends_on,omitempty"`

	// Key Unique key for this job within the workflow
	Key            string                 `json:"key"`
	MaxRetries     *int                   `json:"max_retries,omitempty"`
	Payload        map[string]interface{} `json:"payload"`
	Priority       *int                   `json:"priority,omitempty"`
	QueueName      string                 `json:"queue_name"`
	TimeoutSeconds *int                   `json:"timeout_seconds,omitempty"`
}

// WorkflowJobDefinitionDependencyMode defines model for WorkflowJobDefinition.DependencyMode.
type WorkflowJobDefinitionDependencyMode string

// WorkflowJobMapping defines model for WorkflowJobMapping.
type WorkflowJobMapping struct {
	JobId openapi_types.UUID `json:"job_id"`
	Key   string             `json:"key"`
}

// WorkflowResponse defines model for WorkflowResponse.
type WorkflowResponse struct {
	CompletedAt     *time.Time              `json:"completed_at,omitempty"`
	CompletedJobs   int                     `json:"completed_jobs"`
	CreatedAt       time.Time               `json:"created_at"`
	Description     *string                 `json:"description,omitempty"`
	FailedJobs      int                     `json:"failed_jobs"`
	Id              openapi_types.UUID      `json:"id"`
	Metadata        *map[string]interface{} `json:"metadata,omitempty"`
	Name            string                  `json:"name"`
	ProgressPercent float32                 `json:"progress_percent"`
	StartedAt       *time.Time              `json:"started_at,omitempty"`
	Status          WorkflowResponseStatus  `json:"status"`
	TotalJobs       int                     `json:"total_jobs"`
}

// WorkflowResponseStatus defines model for WorkflowResponse.Status.
type WorkflowResponseStatus string

// AdminListOrganizationsParams defines parameters for AdminListOrganizations.
type AdminListOrganizationsParams struct {
	// PlanTier Filter by plan tier
	PlanTier *AdminListOrganizationsParamsPlanTier `form:"plan_tier,omitempty" json:"plan_tier,omitempty"`

	// Search Search by name or slug
	Search *string `form:"search,omitempty" json:"search,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// AdminListOrganizationsParamsPlanTier defines parameters for AdminListOrganizations.
type AdminListOrganizationsParamsPlanTier string

// AdminDeleteOrganizationParams defines parameters for AdminDeleteOrganization.
type AdminDeleteOrganizationParams struct {
	// HardDelete Permanent deletion (cannot be undone)
	HardDelete *bool `form:"hard_delete,omitempty" json:"hard_delete,omitempty"`
}

// CheckEmailParams defines parameters for CheckEmail.
type CheckEmailParams struct {
	// Email Email address to check
	Email openapi_types.Email `form:"email" json:"email"`
}

// StripeWebhookJSONBody defines parameters for StripeWebhook.
type StripeWebhookJSONBody = map[string]interface{}

// SseEventsHandlerParams defines parameters for SseEventsHandler.
type SseEventsHandlerParams struct {
	Queue *string `form:"queue,omitempty" json:"queue,omitempty"`

	// Events Comma-separated event types to filter
	Events *string `form:"events,omitempty" json:"events,omitempty"`
}

// ListJobsParams defines parameters for ListJobs.
type ListJobsParams struct {
	// QueueName Filter by queue name
	QueueName *string `form:"queue_name,omitempty" json:"queue_name,omitempty"`

	// Status Filter by status
	Status *ListJobsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListJobsParamsStatus defines parameters for ListJobs.
type ListJobsParamsStatus string

// ListDeadLetterQueueParams defines parameters for ListDeadLetterQueue.
type ListDeadLetterQueueParams struct {
	// QueueName Filter by queue name
	QueueName *string `form:"queue_name,omitempty" json:"queue_name,omitempty"`
	Limit     *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset    *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// BatchJobStatusParams defines parameters for BatchJobStatus.
type BatchJobStatusParams struct {
	// Ids Comma-separated list of job IDs
	Ids string `form:"ids" json:"ids"`
}

// CheckSlugParams defines parameters for CheckSlug.
type CheckSlugParams struct {
	// Slug Slug to check
	Slug string `form:"slug" json:"slug"`
}

// ClearWebhookTokenJSONBody defines parameters for ClearWebhookToken.
type ClearWebhookTokenJSONBody struct {
	// Confirm Must be true to confirm clearing the token
	Confirm bool `json:"confirm"`
}

// DeleteQueueParams defines parameters for DeleteQueue.
type DeleteQueueParams struct {
	// DeleteJobs Also delete all jobs in the queue
	DeleteJobs *bool `form:"delete_jobs,omitempty" json:"delete_jobs,omitempty"`
}

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	OrganizationId *string `form:"organization_id,omitempty" json:"organization_id,omitempty"`
	Limit          *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetScheduleHistoryParams defines parameters for GetScheduleHistory.
type GetScheduleHistoryParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// CustomWebhookParams defines parameters for CustomWebhook.
type CustomWebhookParams struct {
	// XWebhookToken Webhook authentication token. Required if the organization has configured
	// a `webhook_token` in their settings.
	XWebhookToken *string `json:"X-Webhook-Token,omitempty"`
}

// ListWorkflowsParams defines parameters for ListWorkflows.
type ListWorkflowsParams struct {
	Status *ListWorkflowsParamsStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *int                       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int                       `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListWorkflowsParamsStatus defines parameters for ListWorkflows.
type ListWorkflowsParamsStatus string

// WebsocketHandlerParams defines parameters for WebsocketHandler.
type WebsocketHandlerParams struct {
	// Token JWT authentication token
	Token string  `form:"token" json:"token"`
	Queue *string `form:"queue,omitempty" json:"queue,omitempty"`
	JobId *string `form:"job_id,omitempty" json:"job_id,omitempty"`

	// Events Comma-separated event types
	Events *string `form:"events,omitempty" json:"events,omitempty"`
}

// AdminCreateOrganizationJSONRequestBody defines body for AdminCreateOrganization for application/json ContentType.
type AdminCreateOrganizationJSONRequestBody = AdminCreateOrganizationRequest

// AdminUpdateOrganizationJSONRequestBody defines body for AdminUpdateOrganization for application/json ContentType.
type AdminUpdateOrganizationJSONRequestBody = AdminUpdateOrganizationRequest

// AdminCreateApiKeyJSONRequestBody defines body for AdminCreateApiKey for application/json ContentType.
type AdminCreateApiKeyJSONRequestBody = CreateApiKeyRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// UpdateApiKeyJSONRequestBody defines body for UpdateApiKey for application/json ContentType.
type UpdateApiKeyJSONRequestBody = UpdateApiKeyRequest

// StartEmailLoginJSONRequestBody defines body for StartEmailLogin for application/json ContentType.
type StartEmailLoginJSONRequestBody = StartEmailLoginRequest

// VerifyEmailCodeJSONRequestBody defines body for VerifyEmailCode for application/json ContentType.
type VerifyEmailCodeJSONRequestBody = VerifyEmailRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CompleteSignupJSONRequestBody defines body for CompleteSignup for application/json ContentType.
type CompleteSignupJSONRequestBody = CompleteSignupRequest

// ValidateTokenJSONRequestBody defines body for ValidateToken for application/json ContentType.
type ValidateTokenJSONRequestBody = ValidateTokenRequest

// CreateBillingPortalJSONRequestBody defines body for CreateBillingPortal for application/json ContentType.
type CreateBillingPortalJSONRequestBody = CreatePortalRequest

// StripeWebhookJSONRequestBody defines body for StripeWebhook for application/json ContentType.
type StripeWebhookJSONRequestBody = StripeWebhookJSONBody

// CreateJobJSONRequestBody defines body for CreateJob for application/json ContentType.
type CreateJobJSONRequestBody = CreateJobRequest

// BulkEnqueueJobsJSONRequestBody defines body for BulkEnqueueJobs for application/json ContentType.
type BulkEnqueueJobsJSONRequestBody = BulkEnqueueRequest

// ClaimJobsJSONRequestBody defines body for ClaimJobs for application/json ContentType.
type ClaimJobsJSONRequestBody = ClaimJobsRequest

// PurgeDeadLetterQueueJSONRequestBody defines body for PurgeDeadLetterQueue for application/json ContentType.
type PurgeDeadLetterQueueJSONRequestBody = PurgeDlqRequest

// RetryDeadLetterJobsJSONRequestBody defines body for RetryDeadLetterJobs for application/json ContentType.
type RetryDeadLetterJobsJSONRequestBody = RetryDlqRequest

// CompleteJobJSONRequestBody defines body for CompleteJob for application/json ContentType.
type CompleteJobJSONRequestBody = CompleteJobRequest

// AddJobDependenciesJSONRequestBody defines body for AddJobDependencies for application/json ContentType.
type AddJobDependenciesJSONRequestBody = AddDependenciesRequest

// FailJobJSONRequestBody defines body for FailJob for application/json ContentType.
type FailJobJSONRequestBody = FailJobRequest

// JobHeartbeatJSONRequestBody defines body for JobHeartbeat for application/json ContentType.
type JobHeartbeatJSONRequestBody = HeartbeatJobRequest

// BoostJobPriorityJSONRequestBody defines body for BoostJobPriority for application/json ContentType.
type BoostJobPriorityJSONRequestBody = BoostPriorityRequest

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = CreateOrganizationRequest

// GenerateSlugJSONRequestBody defines body for GenerateSlug for application/json ContentType.
type GenerateSlugJSONRequestBody = GenerateSlugRequest

// ClearWebhookTokenJSONRequestBody defines body for ClearWebhookToken for application/json ContentType.
type ClearWebhookTokenJSONRequestBody ClearWebhookTokenJSONBody

// UpdateOrganizationJSONRequestBody defines body for UpdateOrganization for application/json ContentType.
type UpdateOrganizationJSONRequestBody = UpdateOrganizationRequest

// CreateOutgoingWebhookJSONRequestBody defines body for CreateOutgoingWebhook for application/json ContentType.
type CreateOutgoingWebhookJSONRequestBody = CreateOutgoingWebhookRequest

// UpdateOutgoingWebhookJSONRequestBody defines body for UpdateOutgoingWebhook for application/json ContentType.
type UpdateOutgoingWebhookJSONRequestBody = UpdateOutgoingWebhookRequest

// UpdateQueueConfigJSONRequestBody defines body for UpdateQueueConfig for application/json ContentType.
type UpdateQueueConfigJSONRequestBody = UpsertQueueConfigRequest

// PauseQueueJSONRequestBody defines body for PauseQueue for application/json ContentType.
type PauseQueueJSONRequestBody = PauseQueueRequest

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateScheduleRequest

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateScheduleRequest

// CustomWebhookJSONRequestBody defines body for CustomWebhook for application/json ContentType.
type CustomWebhookJSONRequestBody = CustomWebhookRequest

// RegisterWorkerJSONRequestBody defines body for RegisterWorker for application/json ContentType.
type RegisterWorkerJSONRequestBody = RegisterWorkerRequest

// WorkerHeartbeatJSONRequestBody defines body for WorkerHeartbeat for application/json ContentType.
type WorkerHeartbeatJSONRequestBody = WorkerHeartbeatRequest

// CreateWorkflowJSONRequestBody defines body for CreateWorkflow for application/json ContentType.
type CreateWorkflowJSONRequestBody = CreateWorkflowRequest

// AsVerifyEmailLoginResponse returns the union data inside the VerifyEmailResponse as a VerifyEmailLoginResponse
func (t VerifyEmailResponse) AsVerifyEmailLoginResponse() (VerifyEmailLoginResponse, error) {
	var body VerifyEmailLoginResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyEmailLoginResponse overwrites any union data inside the VerifyEmailResponse as the provided VerifyEmailLoginResponse
func (t *VerifyEmailResponse) FromVerifyEmailLoginResponse(v VerifyEmailLoginResponse) error {
	v.Type = "login"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyEmailLoginResponse performs a merge with any union data inside the VerifyEmailResponse, using the provided VerifyEmailLoginResponse
func (t *VerifyEmailResponse) MergeVerifyEmailLoginResponse(v VerifyEmailLoginResponse) error {
	v.Type = "login"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVerifyEmailSignupResponse returns the union data inside the VerifyEmailResponse as a VerifyEmailSignupResponse
func (t VerifyEmailResponse) AsVerifyEmailSignupResponse() (VerifyEmailSignupResponse, error) {
	var body VerifyEmailSignupResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVerifyEmailSignupResponse overwrites any union data inside the VerifyEmailResponse as the provided VerifyEmailSignupResponse
func (t *VerifyEmailResponse) FromVerifyEmailSignupResponse(v VerifyEmailSignupResponse) error {
	v.Type = "signup"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVerifyEmailSignupResponse performs a merge with any union data inside the VerifyEmailResponse, using the provided VerifyEmailSignupResponse
func (t *VerifyEmailResponse) MergeVerifyEmailSignupResponse(v VerifyEmailSignupResponse) error {
	v.Type = "signup"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t VerifyEmailResponse) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t VerifyEmailResponse) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "login":
		return t.AsVerifyEmailLoginResponse()
	case "signup":
		return t.AsVerifyEmailSignupResponse()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t VerifyEmailResponse) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *VerifyEmailResponse) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
