// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: spooled.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job status enumeration
type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_SCHEDULED   JobStatus = 2
	JobStatus_JOB_STATUS_PROCESSING  JobStatus = 3
	JobStatus_JOB_STATUS_COMPLETED   JobStatus = 4
	JobStatus_JOB_STATUS_FAILED      JobStatus = 5
	JobStatus_JOB_STATUS_DEADLETTER  JobStatus = 6
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 7
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_SCHEDULED",
		3: "JOB_STATUS_PROCESSING",
		4: "JOB_STATUS_COMPLETED",
		5: "JOB_STATUS_FAILED",
		6: "JOB_STATUS_DEADLETTER",
		7: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_SCHEDULED":   2,
		"JOB_STATUS_PROCESSING":  3,
		"JOB_STATUS_COMPLETED":   4,
		"JOB_STATUS_FAILED":      5,
		"JOB_STATUS_DEADLETTER":  6,
		"JOB_STATUS_CANCELLED":   7,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spooled_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_spooled_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{0}
}

// Job message
type Job struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	QueueName        string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Status           JobStatus              `protobuf:"varint,4,opt,name=status,proto3,enum=spooled.v1.JobStatus" json:"status,omitempty"`
	Payload          *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Result           *structpb.Struct       `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	RetryCount       int32                  `protobuf:"varint,7,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	MaxRetries       int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	LastError        string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Priority         int32                  `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	TimeoutSeconds   int32                  `protobuf:"varint,11,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ScheduledAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	StartedAt        *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	LeaseExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	AssignedWorkerId string                 `protobuf:"bytes,17,opt,name=assigned_worker_id,json=assignedWorkerId,proto3" json:"assigned_worker_id,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,18,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_spooled_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Job) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *Job) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *Job) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Job) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Job) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Job) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Job) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Job) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Job) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Job) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Job) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

func (x *Job) GetAssignedWorkerId() string {
	if x != nil {
		return x.AssignedWorkerId
	}
	return ""
}

func (x *Job) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// Enqueue Request
type EnqueueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueName      string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority       int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	MaxRetries     int32                  `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	ScheduledAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Tags           map[string]string      `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_spooled_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *EnqueueRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *EnqueueRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *EnqueueRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *EnqueueRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *EnqueueRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Enqueue Response
type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"` // false if idempotent (existing job)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_spooled_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *EnqueueResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

// Dequeue Request
type DequeueRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueName         string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	WorkerId          string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseDurationSecs int32                  `protobuf:"varint,3,opt,name=lease_duration_secs,json=leaseDurationSecs,proto3" json:"lease_duration_secs,omitempty"`
	BatchSize         int32                  `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"` // How many jobs to dequeue at once
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_spooled_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *DequeueRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *DequeueRequest) GetLeaseDurationSecs() int32 {
	if x != nil {
		return x.LeaseDurationSecs
	}
	return 0
}

func (x *DequeueRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

// Dequeue Response
type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_spooled_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{4}
}

func (x *DequeueResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// Complete Request
type CompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRequest) Reset() {
	*x = CompleteRequest{}
	mi := &file_spooled_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRequest) ProtoMessage() {}

func (x *CompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRequest.ProtoReflect.Descriptor instead.
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CompleteRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CompleteRequest) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

// Complete Response
type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_spooled_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Fail Request
type FailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Retry         bool                   `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"` // Whether to retry or move to DLQ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_spooled_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{7}
}

func (x *FailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *FailRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FailRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *FailRequest) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

// Fail Response
type FailResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WillRetry          bool                   `protobuf:"varint,2,opt,name=will_retry,json=willRetry,proto3" json:"will_retry,omitempty"`
	NextRetryDelaySecs int32                  `protobuf:"varint,3,opt,name=next_retry_delay_secs,json=nextRetryDelaySecs,proto3" json:"next_retry_delay_secs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FailResponse) Reset() {
	*x = FailResponse{}
	mi := &file_spooled_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailResponse) ProtoMessage() {}

func (x *FailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailResponse.ProtoReflect.Descriptor instead.
func (*FailResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{8}
}

func (x *FailResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FailResponse) GetWillRetry() bool {
	if x != nil {
		return x.WillRetry
	}
	return false
}

func (x *FailResponse) GetNextRetryDelaySecs() int32 {
	if x != nil {
		return x.NextRetryDelaySecs
	}
	return 0
}

// Renew Lease Request
type RenewLeaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	ExtensionSecs int32                  `protobuf:"varint,3,opt,name=extension_secs,json=extensionSecs,proto3" json:"extension_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseRequest) Reset() {
	*x = RenewLeaseRequest{}
	mi := &file_spooled_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseRequest) ProtoMessage() {}

func (x *RenewLeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseRequest.ProtoReflect.Descriptor instead.
func (*RenewLeaseRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{9}
}

func (x *RenewLeaseRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RenewLeaseRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RenewLeaseRequest) GetExtensionSecs() int32 {
	if x != nil {
		return x.ExtensionSecs
	}
	return 0
}

// Renew Lease Response
type RenewLeaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=new_expires_at,json=newExpiresAt,proto3" json:"new_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewLeaseResponse) Reset() {
	*x = RenewLeaseResponse{}
	mi := &file_spooled_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewLeaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewLeaseResponse) ProtoMessage() {}

func (x *RenewLeaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewLeaseResponse.ProtoReflect.Descriptor instead.
func (*RenewLeaseResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{10}
}

func (x *RenewLeaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RenewLeaseResponse) GetNewExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NewExpiresAt
	}
	return nil
}

// Get Job Request
type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_spooled_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// Get Job Response
type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_spooled_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// Get Queue Stats Request
type GetQueueStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsRequest) Reset() {
	*x = GetQueueStatsRequest{}
	mi := &file_spooled_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsRequest) ProtoMessage() {}

func (x *GetQueueStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsRequest.ProtoReflect.Descriptor instead.
func (*GetQueueStatsRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{13}
}

func (x *GetQueueStatsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

// Get Queue Stats Response
type GetQueueStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Pending       int64                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Scheduled     int64                  `protobuf:"varint,3,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	Processing    int64                  `protobuf:"varint,4,opt,name=processing,proto3" json:"processing,omitempty"`
	Completed     int64                  `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        int64                  `protobuf:"varint,6,opt,name=failed,proto3" json:"failed,omitempty"`
	Deadletter    int64                  `protobuf:"varint,7,opt,name=deadletter,proto3" json:"deadletter,omitempty"`
	Total         int64                  `protobuf:"varint,8,opt,name=total,proto3" json:"total,omitempty"`
	MaxAgeMs      int64                  `protobuf:"varint,9,opt,name=max_age_ms,json=maxAgeMs,proto3" json:"max_age_ms,omitempty"` // Age of oldest pending job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueStatsResponse) Reset() {
	*x = GetQueueStatsResponse{}
	mi := &file_spooled_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueStatsResponse) ProtoMessage() {}

func (x *GetQueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueStatsResponse.ProtoReflect.Descriptor instead.
func (*GetQueueStatsResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{14}
}

func (x *GetQueueStatsResponse) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *GetQueueStatsResponse) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *GetQueueStatsResponse) GetScheduled() int64 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *GetQueueStatsResponse) GetProcessing() int64 {
	if x != nil {
		return x.Processing
	}
	return 0
}

func (x *GetQueueStatsResponse) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *GetQueueStatsResponse) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *GetQueueStatsResponse) GetDeadletter() int64 {
	if x != nil {
		return x.Deadletter
	}
	return 0
}

func (x *GetQueueStatsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetQueueStatsResponse) GetMaxAgeMs() int64 {
	if x != nil {
		return x.MaxAgeMs
	}
	return 0
}

// Stream Jobs Request (server-side streaming)
type StreamJobsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueueName         string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	WorkerId          string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseDurationSecs int32                  `protobuf:"varint,3,opt,name=lease_duration_secs,json=leaseDurationSecs,proto3" json:"lease_duration_secs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StreamJobsRequest) Reset() {
	*x = StreamJobsRequest{}
	mi := &file_spooled_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamJobsRequest) ProtoMessage() {}

func (x *StreamJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamJobsRequest.ProtoReflect.Descriptor instead.
func (*StreamJobsRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{15}
}

func (x *StreamJobsRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *StreamJobsRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *StreamJobsRequest) GetLeaseDurationSecs() int32 {
	if x != nil {
		return x.LeaseDurationSecs
	}
	return 0
}

// Process Request (for bidirectional streaming)
type ProcessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*ProcessRequest_Dequeue
	//	*ProcessRequest_Complete
	//	*ProcessRequest_Fail
	//	*ProcessRequest_RenewLease
	Request       isProcessRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_spooled_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessRequest) GetRequest() isProcessRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ProcessRequest) GetDequeue() *DequeueRequest {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_Dequeue); ok {
			return x.Dequeue
		}
	}
	return nil
}

func (x *ProcessRequest) GetComplete() *CompleteRequest {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ProcessRequest) GetFail() *FailRequest {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

func (x *ProcessRequest) GetRenewLease() *RenewLeaseRequest {
	if x != nil {
		if x, ok := x.Request.(*ProcessRequest_RenewLease); ok {
			return x.RenewLease
		}
	}
	return nil
}

type isProcessRequest_Request interface {
	isProcessRequest_Request()
}

type ProcessRequest_Dequeue struct {
	Dequeue *DequeueRequest `protobuf:"bytes,1,opt,name=dequeue,proto3,oneof"`
}

type ProcessRequest_Complete struct {
	Complete *CompleteRequest `protobuf:"bytes,2,opt,name=complete,proto3,oneof"`
}

type ProcessRequest_Fail struct {
	Fail *FailRequest `protobuf:"bytes,3,opt,name=fail,proto3,oneof"`
}

type ProcessRequest_RenewLease struct {
	RenewLease *RenewLeaseRequest `protobuf:"bytes,4,opt,name=renew_lease,json=renewLease,proto3,oneof"`
}

func (*ProcessRequest_Dequeue) isProcessRequest_Request() {}

func (*ProcessRequest_Complete) isProcessRequest_Request() {}

func (*ProcessRequest_Fail) isProcessRequest_Request() {}

func (*ProcessRequest_RenewLease) isProcessRequest_Request() {}

// Process Response (for bidirectional streaming)
type ProcessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ProcessResponse_Job
	//	*ProcessResponse_Complete
	//	*ProcessResponse_Fail
	//	*ProcessResponse_RenewLease
	//	*ProcessResponse_Error
	Response      isProcessResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_spooled_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessResponse) GetResponse() isProcessResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ProcessResponse) GetJob() *Job {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Job); ok {
			return x.Job
		}
	}
	return nil
}

func (x *ProcessResponse) GetComplete() *CompleteResponse {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *ProcessResponse) GetFail() *FailResponse {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Fail); ok {
			return x.Fail
		}
	}
	return nil
}

func (x *ProcessResponse) GetRenewLease() *RenewLeaseResponse {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_RenewLease); ok {
			return x.RenewLease
		}
	}
	return nil
}

func (x *ProcessResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Response.(*ProcessResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isProcessResponse_Response interface {
	isProcessResponse_Response()
}

type ProcessResponse_Job struct {
	Job *Job `protobuf:"bytes,1,opt,name=job,proto3,oneof"`
}

type ProcessResponse_Complete struct {
	Complete *CompleteResponse `protobuf:"bytes,2,opt,name=complete,proto3,oneof"`
}

type ProcessResponse_Fail struct {
	Fail *FailResponse `protobuf:"bytes,3,opt,name=fail,proto3,oneof"`
}

type ProcessResponse_RenewLease struct {
	RenewLease *RenewLeaseResponse `protobuf:"bytes,4,opt,name=renew_lease,json=renewLease,proto3,oneof"`
}

type ProcessResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*ProcessResponse_Job) isProcessResponse_Response() {}

func (*ProcessResponse_Complete) isProcessResponse_Response() {}

func (*ProcessResponse_Fail) isProcessResponse_Response() {}

func (*ProcessResponse_RenewLease) isProcessResponse_Response() {}

func (*ProcessResponse_Error) isProcessResponse_Response() {}

// Error Response
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_spooled_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{18}
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Worker Registration
type RegisterWorkerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueueName      string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	WorkerType     string                 `protobuf:"bytes,3,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Version        string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_spooled_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterWorkerRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *RegisterWorkerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterWorkerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Worker Registration Response
type RegisterWorkerResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	WorkerId              string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	LeaseDurationSecs     int32                  `protobuf:"varint,2,opt,name=lease_duration_secs,json=leaseDurationSecs,proto3" json:"lease_duration_secs,omitempty"`
	HeartbeatIntervalSecs int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_secs,json=heartbeatIntervalSecs,proto3" json:"heartbeat_interval_secs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_spooled_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterWorkerResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerResponse) GetLeaseDurationSecs() int32 {
	if x != nil {
		return x.LeaseDurationSecs
	}
	return 0
}

func (x *RegisterWorkerResponse) GetHeartbeatIntervalSecs() int32 {
	if x != nil {
		return x.HeartbeatIntervalSecs
	}
	return 0
}

// Heartbeat Request
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	CurrentJobs   int32                  `protobuf:"varint,2,opt,name=current_jobs,json=currentJobs,proto3" json:"current_jobs,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_spooled_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{21}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetCurrentJobs() int32 {
	if x != nil {
		return x.CurrentJobs
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Heartbeat Response
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ShouldDrain   bool                   `protobuf:"varint,2,opt,name=should_drain,json=shouldDrain,proto3" json:"should_drain,omitempty"` // Signal to worker to stop accepting new jobs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_spooled_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{22}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetShouldDrain() bool {
	if x != nil {
		return x.ShouldDrain
	}
	return false
}

// Deregister Request
type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_spooled_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{23}
}

func (x *DeregisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// Deregister Response
type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_spooled_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spooled_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_spooled_proto_rawDescGZIP(), []int{24}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_spooled_proto protoreflect.FileDescriptor

const file_spooled_proto_rawDesc = "" +
	"\n" +
	"\rspooled.proto\x12\n" +
	"spooled.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xa7\x06\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.spooled.v1.JobStatusR\x06status\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12/\n" +
	"\x06result\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1f\n" +
	"\vretry_count\x18\a \x01(\x05R\n" +
	"retryCount\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\x12\x1a\n" +
	"\bpriority\x18\n" +
	" \x01(\x05R\bpriority\x12'\n" +
	"\x0ftimeout_seconds\x18\v \x01(\x05R\x0etimeoutSeconds\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fscheduled_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x129\n" +
	"\n" +
	"started_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12D\n" +
	"\x10lease_expires_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\x12,\n" +
	"\x12assigned_worker_id\x18\x11 \x01(\tR\x10assignedWorkerId\x12'\n" +
	"\x0fidempotency_key\x18\x12 \x01(\tR\x0eidempotencyKey\"\xa3\x03\n" +
	"\x0eEnqueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\x05R\n" +
	"maxRetries\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12=\n" +
	"\fscheduled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x128\n" +
	"\x04tags\x18\b \x03(\v2$.spooled.v1.EnqueueRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0fEnqueueResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"\x9b\x01\n" +
	"\x0eDequeueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12.\n" +
	"\x13lease_duration_secs\x18\x03 \x01(\x05R\x11leaseDurationSecs\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\"6\n" +
	"\x0fDequeueResponse\x12#\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0f.spooled.v1.JobR\x04jobs\"v\n" +
	"\x0fCompleteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12/\n" +
	"\x06result\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06result\",\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"m\n" +
	"\vFailRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x14\n" +
	"\x05retry\x18\x04 \x01(\bR\x05retry\"z\n" +
	"\fFailResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"will_retry\x18\x02 \x01(\bR\twillRetry\x121\n" +
	"\x15next_retry_delay_secs\x18\x03 \x01(\x05R\x12nextRetryDelaySecs\"n\n" +
	"\x11RenewLeaseRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12%\n" +
	"\x0eextension_secs\x18\x03 \x01(\x05R\rextensionSecs\"p\n" +
	"\x12RenewLeaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12@\n" +
	"\x0enew_expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fnewExpiresAt\"&\n" +
	"\rGetJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"3\n" +
	"\x0eGetJobResponse\x12!\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.spooled.v1.JobR\x03job\"5\n" +
	"\x14GetQueueStatsRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"\x98\x02\n" +
	"\x15GetQueueStatsResponse\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x18\n" +
	"\apending\x18\x02 \x01(\x03R\apending\x12\x1c\n" +
	"\tscheduled\x18\x03 \x01(\x03R\tscheduled\x12\x1e\n" +
	"\n" +
	"processing\x18\x04 \x01(\x03R\n" +
	"processing\x12\x1c\n" +
	"\tcompleted\x18\x05 \x01(\x03R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x06 \x01(\x03R\x06failed\x12\x1e\n" +
	"\n" +
	"deadletter\x18\a \x01(\x03R\n" +
	"deadletter\x12\x14\n" +
	"\x05total\x18\b \x01(\x03R\x05total\x12\x1c\n" +
	"\n" +
	"max_age_ms\x18\t \x01(\x03R\bmaxAgeMs\"\x7f\n" +
	"\x11StreamJobsRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12.\n" +
	"\x13lease_duration_secs\x18\x03 \x01(\x05R\x11leaseDurationSecs\"\xff\x01\n" +
	"\x0eProcessRequest\x126\n" +
	"\adequeue\x18\x01 \x01(\v2\x1a.spooled.v1.DequeueRequestH\x00R\adequeue\x129\n" +
	"\bcomplete\x18\x02 \x01(\v2\x1b.spooled.v1.CompleteRequestH\x00R\bcomplete\x12-\n" +
	"\x04fail\x18\x03 \x01(\v2\x17.spooled.v1.FailRequestH\x00R\x04fail\x12@\n" +
	"\vrenew_lease\x18\x04 \x01(\v2\x1d.spooled.v1.RenewLeaseRequestH\x00R\n" +
	"renewLeaseB\t\n" +
	"\arequest\"\xa4\x02\n" +
	"\x0fProcessResponse\x12#\n" +
	"\x03job\x18\x01 \x01(\v2\x0f.spooled.v1.JobH\x00R\x03job\x12:\n" +
	"\bcomplete\x18\x02 \x01(\v2\x1c.spooled.v1.CompleteResponseH\x00R\bcomplete\x12.\n" +
	"\x04fail\x18\x03 \x01(\v2\x18.spooled.v1.FailResponseH\x00R\x04fail\x12A\n" +
	"\vrenew_lease\x18\x04 \x01(\v2\x1e.spooled.v1.RenewLeaseResponseH\x00R\n" +
	"renewLease\x121\n" +
	"\x05error\x18\x05 \x01(\v2\x19.spooled.v1.ErrorResponseH\x00R\x05errorB\n" +
	"\n" +
	"\bresponse\"=\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc0\x02\n" +
	"\x15RegisterWorkerRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1f\n" +
	"\vworker_type\x18\x03 \x01(\tR\n" +
	"workerType\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.spooled.v1.RegisterWorkerRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x16RegisterWorkerResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12.\n" +
	"\x13lease_duration_secs\x18\x02 \x01(\x05R\x11leaseDurationSecs\x126\n" +
	"\x17heartbeat_interval_secs\x18\x03 \x01(\x05R\x15heartbeatIntervalSecs\"\xef\x01\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12!\n" +
	"\fcurrent_jobs\x18\x02 \x01(\x05R\vcurrentJobs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12F\n" +
	"\bmetadata\x18\x04 \x03(\v2*.spooled.v1.HeartbeatRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12!\n" +
	"\fshould_drain\x18\x02 \x01(\bR\vshouldDrain\"0\n" +
	"\x11DeregisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\xda\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14JOB_STATUS_SCHEDULED\x10\x02\x12\x19\n" +
	"\x15JOB_STATUS_PROCESSING\x10\x03\x12\x18\n" +
	"\x14JOB_STATUS_COMPLETED\x10\x04\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x05\x12\x19\n" +
	"\x15JOB_STATUS_DEADLETTER\x10\x06\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\a2\x88\x05\n" +
	"\fQueueService\x12B\n" +
	"\aEnqueue\x12\x1a.spooled.v1.EnqueueRequest\x1a\x1b.spooled.v1.EnqueueResponse\x12B\n" +
	"\aDequeue\x12\x1a.spooled.v1.DequeueRequest\x1a\x1b.spooled.v1.DequeueResponse\x12E\n" +
	"\bComplete\x12\x1b.spooled.v1.CompleteRequest\x1a\x1c.spooled.v1.CompleteResponse\x129\n" +
	"\x04Fail\x12\x17.spooled.v1.FailRequest\x1a\x18.spooled.v1.FailResponse\x12K\n" +
	"\n" +
	"RenewLease\x12\x1d.spooled.v1.RenewLeaseRequest\x1a\x1e.spooled.v1.RenewLeaseResponse\x12?\n" +
	"\x06GetJob\x12\x19.spooled.v1.GetJobRequest\x1a\x1a.spooled.v1.GetJobResponse\x12T\n" +
	"\rGetQueueStats\x12 .spooled.v1.GetQueueStatsRequest\x1a!.spooled.v1.GetQueueStatsResponse\x12>\n" +
	"\n" +
	"StreamJobs\x12\x1d.spooled.v1.StreamJobsRequest\x1a\x0f.spooled.v1.Job0\x01\x12J\n" +
	"\vProcessJobs\x12\x1a.spooled.v1.ProcessRequest\x1a\x1b.spooled.v1.ProcessResponse(\x010\x012\xf9\x01\n" +
	"\rWorkerService\x12Q\n" +
	"\bRegister\x12!.spooled.v1.RegisterWorkerRequest\x1a\".spooled.v1.RegisterWorkerResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.spooled.v1.HeartbeatRequest\x1a\x1d.spooled.v1.HeartbeatResponse\x12K\n" +
	"\n" +
	"Deregister\x12\x1d.spooled.v1.DeregisterRequest\x1a\x1e.spooled.v1.DeregisterResponseB9Z7github.com/spooled-cloud/spooled-sdk-go/spooled/grpc/pbb\x06proto3"

var (
	file_spooled_proto_rawDescOnce sync.Once
	file_spooled_proto_rawDescData []byte
)

func file_spooled_proto_rawDescGZIP() []byte {
	file_spooled_proto_rawDescOnce.Do(func() {
		file_spooled_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spooled_proto_rawDesc), len(file_spooled_proto_rawDesc)))
	})
	return file_spooled_proto_rawDescData
}

var file_spooled_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spooled_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_spooled_proto_goTypes = []any{
	(JobStatus)(0),                 // 0: spooled.v1.JobStatus
	(*Job)(nil),                    // 1: spooled.v1.Job
	(*EnqueueRequest)(nil),         // 2: spooled.v1.EnqueueRequest
	(*EnqueueResponse)(nil),        // 3: spooled.v1.EnqueueResponse
	(*DequeueRequest)(nil),         // 4: spooled.v1.DequeueRequest
	(*DequeueResponse)(nil),        // 5: spooled.v1.DequeueResponse
	(*CompleteRequest)(nil),        // 6: spooled.v1.CompleteRequest
	(*CompleteResponse)(nil),       // 7: spooled.v1.CompleteResponse
	(*FailRequest)(nil),            // 8: spooled.v1.FailRequest
	(*FailResponse)(nil),           // 9: spooled.v1.FailResponse
	(*RenewLeaseRequest)(nil),      // 10: spooled.v1.RenewLeaseRequest
	(*RenewLeaseResponse)(nil),     // 11: spooled.v1.RenewLeaseResponse
	(*GetJobRequest)(nil),          // 12: spooled.v1.GetJobRequest
	(*GetJobResponse)(nil),         // 13: spooled.v1.GetJobResponse
	(*GetQueueStatsRequest)(nil),   // 14: spooled.v1.GetQueueStatsRequest
	(*GetQueueStatsResponse)(nil),  // 15: spooled.v1.GetQueueStatsResponse
	(*StreamJobsRequest)(nil),      // 16: spooled.v1.StreamJobsRequest
	(*ProcessRequest)(nil),         // 17: spooled.v1.ProcessRequest
	(*ProcessResponse)(nil),        // 18: spooled.v1.ProcessResponse
	(*ErrorResponse)(nil),          // 19: spooled.v1.ErrorResponse
	(*RegisterWorkerRequest)(nil),  // 20: spooled.v1.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 21: spooled.v1.RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 22: spooled.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 23: spooled.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),      // 24: spooled.v1.DeregisterRequest
	(*DeregisterResponse)(nil),     // 25: spooled.v1.DeregisterResponse
	nil,                            // 26: spooled.v1.EnqueueRequest.TagsEntry
	nil,                            // 27: spooled.v1.RegisterWorkerRequest.MetadataEntry
	nil,                            // 28: spooled.v1.HeartbeatRequest.MetadataEntry
	(*structpb.Struct)(nil),        // 29: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 30: google.protobuf.Timestamp
}
var file_spooled_proto_depIdxs = []int32{
	0,  // 0: spooled.v1.Job.status:type_name -> spooled.v1.JobStatus
	29, // 1: spooled.v1.Job.payload:type_name -> google.protobuf.Struct
	29, // 2: spooled.v1.Job.result:type_name -> google.protobuf.Struct
	30, // 3: spooled.v1.Job.created_at:type_name -> google.protobuf.Timestamp
	30, // 4: spooled.v1.Job.scheduled_at:type_name -> google.protobuf.Timestamp
	30, // 5: spooled.v1.Job.started_at:type_name -> google.protobuf.Timestamp
	30, // 6: spooled.v1.Job.completed_at:type_name -> google.protobuf.Timestamp
	30, // 7: spooled.v1.Job.lease_expires_at:type_name -> google.protobuf.Timestamp
	29, // 8: spooled.v1.EnqueueRequest.payload:type_name -> google.protobuf.Struct
	30, // 9: spooled.v1.EnqueueRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	26, // 10: spooled.v1.EnqueueRequest.tags:type_name -> spooled.v1.EnqueueRequest.TagsEntry
	1,  // 11: spooled.v1.DequeueResponse.jobs:type_name -> spooled.v1.Job
	29, // 12: spooled.v1.CompleteRequest.result:type_name -> google.protobuf.Struct
	30, // 13: spooled.v1.RenewLeaseResponse.new_expires_at:type_name -> google.protobuf.Timestamp
	1,  // 14: spooled.v1.GetJobResponse.job:type_name -> spooled.v1.Job
	4,  // 15: spooled.v1.ProcessRequest.dequeue:type_name -> spooled.v1.DequeueRequest
	6,  // 16: spooled.v1.ProcessRequest.complete:type_name -> spooled.v1.CompleteRequest
	8,  // 17: spooled.v1.ProcessRequest.fail:type_name -> spooled.v1.FailRequest
	10, // 18: spooled.v1.ProcessRequest.renew_lease:type_name -> spooled.v1.RenewLeaseRequest
	1,  // 19: spooled.v1.ProcessResponse.job:type_name -> spooled.v1.Job
	7,  // 20: spooled.v1.ProcessResponse.complete:type_name -> spooled.v1.CompleteResponse
	9,  // 21: spooled.v1.ProcessResponse.fail:type_name -> spooled.v1.FailResponse
	11, // 22: spooled.v1.ProcessResponse.renew_lease:type_name -> spooled.v1.RenewLeaseResponse
	19, // 23: spooled.v1.ProcessResponse.error:type_name -> spooled.v1.ErrorResponse
	27, // 24: spooled.v1.RegisterWorkerRequest.metadata:type_name -> spooled.v1.RegisterWorkerRequest.MetadataEntry
	28, // 25: spooled.v1.HeartbeatRequest.metadata:type_name -> spooled.v1.HeartbeatRequest.MetadataEntry
	2,  // 26: spooled.v1.QueueService.Enqueue:input_type -> spooled.v1.EnqueueRequest
	4,  // 27: spooled.v1.QueueService.Dequeue:input_type -> spooled.v1.DequeueRequest
	6,  // 28: spooled.v1.QueueService.Complete:input_type -> spooled.v1.CompleteRequest
	8,  // 29: spooled.v1.QueueService.Fail:input_type -> spooled.v1.FailRequest
	10, // 30: spooled.v1.QueueService.RenewLease:input_type -> spooled.v1.RenewLeaseRequest
	12, // 31: spooled.v1.QueueService.GetJob:input_type -> spooled.v1.GetJobRequest
	14, // 32: spooled.v1.QueueService.GetQueueStats:input_type -> spooled.v1.GetQueueStatsRequest
	16, // 33: spooled.v1.QueueService.StreamJobs:input_type -> spooled.v1.StreamJobsRequest
	17, // 34: spooled.v1.QueueService.ProcessJobs:input_type -> spooled.v1.ProcessRequest
	20, // 35: spooled.v1.WorkerService.Register:input_type -> spooled.v1.RegisterWorkerRequest
	22, // 36: spooled.v1.WorkerService.Heartbeat:input_type -> spooled.v1.HeartbeatRequest
	24, // 37: spooled.v1.WorkerService.Deregister:input_type -> spooled.v1.DeregisterRequest
	3,  // 38: spooled.v1.QueueService.Enqueue:output_type -> spooled.v1.EnqueueResponse
	5,  // 39: spooled.v1.QueueService.Dequeue:output_type -> spooled.v1.DequeueResponse
	7,  // 40: spooled.v1.QueueService.Complete:output_type -> spooled.v1.CompleteResponse
	9,  // 41: spooled.v1.QueueService.Fail:output_type -> spooled.v1.FailResponse
	11, // 42: spooled.v1.QueueService.RenewLease:output_type -> spooled.v1.RenewLeaseResponse
	13, // 43: spooled.v1.QueueService.GetJob:output_type -> spooled.v1.GetJobResponse
	15, // 44: spooled.v1.QueueService.GetQueueStats:output_type -> spooled.v1.GetQueueStatsResponse
	1,  // 45: spooled.v1.QueueService.StreamJobs:output_type -> spooled.v1.Job
	18, // 46: spooled.v1.QueueService.ProcessJobs:output_type -> spooled.v1.ProcessResponse
	21, // 47: spooled.v1.WorkerService.Register:output_type -> spooled.v1.RegisterWorkerResponse
	23, // 48: spooled.v1.WorkerService.Heartbeat:output_type -> spooled.v1.HeartbeatResponse
	25, // 49: spooled.v1.WorkerService.Deregister:output_type -> spooled.v1.DeregisterResponse
	38, // [38:50] is the sub-list for method output_type
	26, // [26:38] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_spooled_proto_init() }
func file_spooled_proto_init() {
	if File_spooled_proto != nil {
		return
	}
	file_spooled_proto_msgTypes[16].OneofWrappers = []any{
		(*ProcessRequest_Dequeue)(nil),
		(*ProcessRequest_Complete)(nil),
		(*ProcessRequest_Fail)(nil),
		(*ProcessRequest_RenewLease)(nil),
	}
	file_spooled_proto_msgTypes[17].OneofWrappers = []any{
		(*ProcessResponse_Job)(nil),
		(*ProcessResponse_Complete)(nil),
		(*ProcessResponse_Fail)(nil),
		(*ProcessResponse_RenewLease)(nil),
		(*ProcessResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spooled_proto_rawDesc), len(file_spooled_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_spooled_proto_goTypes,
		DependencyIndexes: file_spooled_proto_depIdxs,
		EnumInfos:         file_spooled_proto_enumTypes,
		MessageInfos:      file_spooled_proto_msgTypes,
	}.Build()
	File_spooled_proto = out.File
	file_spooled_proto_goTypes = nil
	file_spooled_proto_depIdxs = nil
}
